# Generated by Django 4.1 on 2022-12-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_join', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=60)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCart', models.IntegerField(primary_key=True, serialize=False, verbose_name='idCart')),
                ('productoId', models.IntegerField(verbose_name='productoId')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='pedido')),
                ('idComprador', models.IntegerField(verbose_name='idCliente')),
                ('pedidoDate', models.DateTimeField(verbose_name='fechaPedido')),
                ('estado', models.TextField(max_length=20, verbose_name='estadoPedido')),
                ('precio', models.IntegerField(verbose_name='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='idProducto')),
                ('nombreProducto', models.CharField(max_length=255, verbose_name='nombre')),
                ('autor', models.CharField(max_length=255, verbose_name='autor')),
                ('precioProducto', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(upload_to='productos')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
        ),
    ]
